from __future__ import annotations

from datetime import datetime, timezone

import pandas as pd


def generate_weekly_bulletin(
    new_failures: pd.DataFrame,
    new_passes: pd.DataFrame,
    dashboard_url: str,
    commit_sha: str,
) -> str:
    """Create markdown-ready bulletin for Slack or forum updates."""
    timestamp = datetime.now(timezone.utc).strftime("%Y-%m-%d %H:%M UTC")

    lines = [
        "## Open edX Repo Health Weekly Bulletin",
        f"Generated: {timestamp}",
        "",
        "### Newly failing checks",
    ]

    if new_failures.empty:
        lines.append("- None")
    else:
        for _, row in new_failures.head(20).iterrows():
            lines.append(f"- {row['repo_name']}: {row['check']}")

    lines.extend(["", "### Newly passing checks"])
    if new_passes.empty:
        lines.append("- None")
    else:
        for _, row in new_passes.head(20).iterrows():
            lines.append(f"- {row['repo_name']}: {row['check']}")

    lines.extend(["", f"Dashboard: {dashboard_url}"])
    # Only emit the provenance line for a real build. GITHUB_SHA is unset
    # locally, so the caller passes "local", and anyone copying a bulletin from a
    # dev run was pasting "Commit: local" into Slack.
    if commit_sha and commit_sha.strip().lower() not in {"local", "unknown", "none"}:
        lines.append(f"Commit: {commit_sha}")
    lines.append("Generated by Open edX Repository Health Dashboard")
    return "\n".join(lines)
