from __future__ import annotations

from pathlib import Path

import streamlit as st


ROOT = Path(__file__).resolve().parents[1]
CARDS_DIR = ROOT / "dashboards" / "cards"
YEAR_REVIEW = CARDS_DIR / "year-in-review.html"
EMBEDS_DIR = CARDS_DIR / "embeds"


def render() -> None:
    st.title("Year-in-review and Embeddable Cards")
    st.caption("Phase 2 static artifacts generated by scripts/generate_phase2_cards.py")

    st.code("python scripts/generate_phase2_cards.py", language="bash")

    st.subheader("Year in review")
    if YEAR_REVIEW.exists():
        st.success(f"Found generated file: {YEAR_REVIEW.relative_to(ROOT)}")
        st.download_button(
            "Download year-in-review HTML",
            data=YEAR_REVIEW.read_text(encoding="utf-8"),
            file_name="year-in-review.html",
            mime="text/html",
        )
    else:
        st.info("No year-in-review file found yet.")

    st.subheader("Embeddable repo cards")
    if EMBEDS_DIR.exists():
        cards = sorted(EMBEDS_DIR.glob("*.html"))
        st.write(f"Generated cards: {len(cards)}")
        for card in cards[:100]:
            st.write(card.relative_to(ROOT).as_posix())
    else:
        st.info("No embed cards found yet.")


render()
